legacy_layout=false

# General Settings
background_alpha=0.4
round_corners=0
background_alpha=0.4
background_color=1A1B1F
font_size=20
text_color=DADBDD
position=top-left
toggle_hud=Shift_R+F12
pci_dev=0:01:00.0
table_columns=3

# CPU
cpu_text=CPU
cpu_stats
cpu_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_temp
cpu_color=4993C6

# GPU
gpu_text=GPU
gpu_stats
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_temp
gpu_color=65AD5F

# VRAM
vram
vram_color=DADBDD

# RAM
ram
ram_color=DADBDD

# FPS
fps
fps_metrics=avg
fps_limit_method=late
toggle_fps_limit=Shift_L+F1
fps_limit=0

# Log
output_folder=/home/sharkthak
log_duration=30
autostart_log=0
log_interval=100
toggle_logging=Shift_L+F2

# Blacklist
blacklist=pamac-manager,lact,ghb,bitwig-studio,ptyxis,yumex
