dir=/home/sharkthak/Downloads/

continue=true
quiet=false
max-connection-per-server=10
max-concurrent-downloads=5
max-overall-download-limit=0
max-download-limit=0
min-split-size=5M
log=
log-level=error
console-log-level=error
auto-file-renaming=true
disk-cache=64M
summary-interval=0
