#!/usr/bin/env bash
set -euo pipefail

# Speaker ID
function get_speaker_id {
    local speaker="700 Series Chipset Family HD Audio Speaker"
    local sinks=$(wpctl status | grep -A7 "Sinks:" | grep "$speaker" || true)
    local node_id="${sinks##*│}"    # remove leading non-digit characters to isolate the id
    node_id="${node_id%%.*}"            # keep only up to the first '.'
    node_id="${node_id//[[:space:]]/}"  # strip all whitespace
    node_id="${node_id#\*}"          # remove leading * if present
    if [[ -n "$node_id" ]]; then
            echo "$node_id"
            return 0
        else
            return 1
        fi
}

# buds id
function get_buds_id {
    local buds="CMF Buds Pro 2"
    local sinks=$(wpctl status | grep -A7 "Sinks:" | grep "$buds" || true)
    if [[ -z "$sinks" ]]; then
        notify-send -t 2000 "Error" "Buds not connected"  # Error popup
        return 1
    fi
    local node_id="${sinks##*│}"    # remove leading non-digit characters to isolate the id
    node_id="${node_id%%.*}"            # keep only up to the first '.'
    node_id="${node_id//[[:space:]]/}"  # strip all whitespace
    node_id="${node_id#\*}"          # remove leading * if present
    if [[ -n "$node_id" ]]; then
            echo "$node_id"
            return 0
        else
            return 1
        fi
}

buds_id=$(get_buds_id) || exit 1
speaker_id=$(get_speaker_id) || exit 1

current_default=$(wpctl status | sed -n '/Sinks:/,/^ ├─ /{ /^ ├─ /!p }' | grep '\*')
current_default="${current_default##*│}"    # remove leading non-digit characters to isolate the id
current_default="${current_default%%.*}"            # keep only up to the first '.'
current_default="${current_default//[[:space:]]/}"  # strip all whitespace
current_default="${current_default#\*}"     # removes leading * if present

if [[ "$current_default" = "$speaker_id" ]]; then
    wpctl set-default "$buds_id"
elif [[ "$current_default" = "$buds_id" ]]; then
    wpctl set-default "$speaker_id"
else
    notify-send -t 2000 "Error" "Unknown default device"
fi
