#!/bin/sh

PLAYER_STATUS=$(playerctl status 2>/dev/null)

if [ "$PLAYER_STATUS" = "Playing" ]; then
    echo "▶ $(playerctl metadata --format '{{ artist }} - {{ title }}')"
elif [ "$PLAYER_STATUS" = "Paused" ]; then
    echo "⏸ $(playerctl metadata --format '{{ artist }} - {{ title }}')"
else
    echo ""
fi
