#!/bin/sh

PLAYER_STATUS=$(playerctl status -p spotify 2>/dev/null)

if [ "$PLAYER_STATUS" = "Playing" ]; then
    echo "▶ $(playerctl metadata --format '{{ title }} - {{ artist }}' -p spotify)"
elif [ "$PLAYER_STATUS" = "Paused" ]; then
    echo "⏸ $(playerctl metadata --format '{{ title }} - {{ artist }}' -p spotify)"
else
    echo ""
fi
