exec-once = $browser
exec-once = $music
exec-once = $notes
exec-once = mako &
exec-once = hyprpaper
exec-once = hypridle
exec-once = bottles
exec-once = discord

exec-once = bluetoothctl connect 2C:BE:EB:DE:96:D2		# Connect to my CMF buds
exec-once = kdeconnect-cli --list-available		# Running this will connect

exec-once=/usr/lib/polkit-kde-authentication-agent-1

