background {
    monitor =
    path = ~/.config/wallpapers/pixel-deer.png
    blur_passes = 2
    blur_size = 2
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(c75465)
    inner_color = rgb(1a1b1f)
    font_color = rgb(dadbdd)
    font_family = JetBrainsMono Nerd Font Semibold
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Enter Password</i>
    hide_input = false
    rounding = -1
    check_color = rgb(65ad5f)
    fail_color = rgb(d04a3b)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 100
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgb(dadbdd)
    font_size = 55
    font_family = JetBrainsMono Nerd Font Semibold
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:500] ~/.config/hypr/scripts/get-media-info
    color = rgb(dadbdd)
    font_size = 30
    font_family = JetBrainsMono Nerd Font Semibold
    position = 0, -350
    halign = center
    valign = center
    onclick = playerctl play-pause
}

label {
    monitor =
    text = cmd[update:5000] echo "$(curl -s 'wttr.in/Bhopal?format=%C+%t' 2>/dev/null)"
    color = rgb(dadbdd)
    font_size = 15
    font_family = JetBrainsMono Nerd Font Semibold
    position = 0, 125
    halign = center
    valign = center
}
