background = 0xFF1A1B1F
base = 0xFF2A2B2F
alternate_base = 0xFF3B3C3F
text = 0xFFDADBDD
bright_text = 0xFFDADBDD
accent = 0xFFC75465
accent_secondary = 0xFFC75465
h1_size = 40
h2_size = 24
h3_size = 16
font_size = 12
small_font_size = 10
icon_theme =
font_family = Sans Serif
font_family_monospace = monospace
rounding_large = 10
rounding_small = 5
