monitor = ,highres,auto,1

source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
