input {
    kb_layout = us
    kb_options = caps:swapescape

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        scroll_factor = 0.33
	      natural_scroll = true
    }
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
}

