$mainMod = SUPER

bind = $mainMod, Escape, exec, killall waybar || waybar
bind = $mainMod, F, exec, hyprctl dispatch fullscreenstate 1 0
bind = $mainMod, Q, killactive,
bind = $mainMod CTRL SHIFT, X, exit,
bind = $mainMod, Space, exec, $menu
bind = $mainMod, T, exec, $terminal
bind = $mainMod, N, exec, $code
bind = $mainMod, E, exec, $filemanager
bind = $mainMod, W, exec, $browser
bind = $mainMod, S, exec, $music
bind = $mainMod, V, togglefloating,
bind = $mainMod CTRL, S, exec, hyprshot -s -m region --clipboard-only --freeze		# Capture region and copy
bind = $mainMod SHIFT, S, exec, hyprshot -s -m window -m active -o ~/Pictures/Screenshots -f grab.png		# Capture active window and copy
bind = $mainMod, C, exec, hyprpicker -arl
bind = $mainMod, L, exec, hyprlock

bind = $mainMod SHIFT, C, exec, kdeconnect-cli --send-clipboard -n nord3		# KDE Connect send clipboard

bind = $mainMod SHIFT, A, exec, ~/.config/hypr/scripts/audioToggle.sh		# Audio output toggle
bind = $mainMod SHIFT, F, exec, ~/.config/hypr/scripts/kde-file-share.sh		# KDE Connect file sharing

bind = $mainMod, TAB, cyclenext

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, grave, togglespecialworkspace, terminal

bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, grave, movetoworkspace, special:terminal

bind = $mainMod, G, togglegroup
bind = $mainMod, Tab, changegroupactive, f

bind = $mainMod, mouse_down, workspace, e-1
bind = $mainMod, mouse_up, workspace, e+1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bind = CTRL ALT, S, exec, playerctl --player=spotify play-pause # Spotify only play/plause 
bind = CTRL ALT, D, exec, playerctl --player=spotify next		# Spotify only next track
bind = CTRL ALT, A, exec, playerctl --player=spotify previous	# Spotify only previous track

