$mod = SUPER

bind = $mod, Escape, exec, hyprpanel toggleWindow bar-0

bind = $mod, F, exec, hyprctl dispatch fullscreenstate 1 0
bind = $mod SHIFT, F, exec, hyprctl dispatch fullscreenstate 2 0

bind = $mod, Q, killactive,
bind = $mod, V, togglefloating,

bind = $mod CTRL SHIFT, X, exit,

# Launchers
bind = $mod, Space, exec, $menu
bind = $mod, T, exec, $terminal
bind = $mod, N, exec, $code
bind = $mod, E, exec, $filemanager
bind = $mod, W, exec, $browser
bind = $mod, S, exec, $music
bind = $mod, B, exec, $video
bind = $mod, B, exec, beeper

bind = $mod, V, togglefloating,
bind = $mod, TAB, cyclenext
bind = $mod, TAB, bringactivetotop

# Hypr ecosystem
bind = $mod CTRL, S, exec, hyprshot -s -m region --clipboard-only --freeze		# Capture region and copy
bind = $mod SHIFT, S, exec, hyprshot -s -m window -m active -o ~/Pictures/Screenshots -f grab.png		# Capture active window and copy
bind = $mod, C, exec, hyprpicker -arl
bind = $mod, L, exec, hyprlock

# KDE-Connect
bind = $mod CTRL, C, exec, kdeconnect-cli --send-clipboard -n nord3		# KDE Connect send clipboard
bind = $mod CTRL, F, exec, ~/.config/hypr/scripts/kde-file-share  		# KDE Connect file sharing

# Scripts
bind = $mod SHIFT, A, exec, ~/.config/hypr/scripts/audio-toggle       # Audio output toggle
bind = $mod SHIFT, B, exec, ~/.config/hypr/scripts/battery-notif      # Display battery status of things

# Spotify
bind = CTRL ALT, S, exec, playerctl --player=spotify play-pause
bind = CTRL ALT, D, exec, playerctl --player=spotify next
bind = CTRL ALT, A, exec, playerctl --player=spotify previous

# GPU Screen Recorder
bind = $mod SHIFT, R, exec, gsr-ui-cli toggle-replay
bind = $mod, R, exec, gsr-ui-cli replay-save

# Minimize windows
bind = $mod, D, togglespecialworkspace, minimize
bind = $mod, D, movetoworkspace, +0
bind = $mod, D, togglespecialworkspace, minimize
bind = $mod, D, movetoworkspace, special:minimize
bind = $mod, D, togglespecialworkspace, minimize

# Windows
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, grave, togglespecialworkspace, terminal

bind = $mod CTRL, 1, movetoworkspace, 1
bind = $mod CTRL, 2, movetoworkspace, 2
bind = $mod CTRL, 3, movetoworkspace, 3
bind = $mod CTRL, 4, movetoworkspace, 4
bind = $mod CTRL, grave, movetoworkspace, special:terminal

# Function Keys
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
