$mod = SUPER

bind = $mod, Escape, exec, killall waybar || waybar
bind = $mod, F, exec, hyprctl dispatch fullscreenstate 1 0
bind = $mod, Q, killactive,
bind = $mod CTRL SHIFT, X, exit,
bind = $mod, Space, exec, $menu
bind = $mod, T, exec, $terminal
bind = $mod, N, exec, $code
bind = $mod, E, exec, $filemanager
bind = $mod, W, exec, $browser
bind = $mod, S, exec, $music
bind = $mod, V, togglefloating,
bind = $mod CTRL, S, exec, hyprshot -s -m region --clipboard-only --freeze		# Capture region and copy
bind = $mod SHIFT, S, exec, hyprshot -s -m window -m active -o ~/Pictures/Screenshots -f grab.png		# Capture active window and copy
bind = $mod, C, exec, hyprpicker -arl
bind = $mod, L, exec, hyprlock

bind = $mod SHIFT, C, exec, kdeconnect-cli --send-clipboard -n nord3		# KDE Connect send clipboard

bind = $mod SHIFT, A, exec, ~/.config/hypr/scripts/audio-toggle.sh		# Audio output toggle
bind = $mod SHIFT, F, exec, ~/.config/hypr/scripts/kde-file-share.sh		# KDE Connect file sharing

bind = $mod, TAB, cyclenext

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, grave, togglespecialworkspace, terminal

bind = $mod CTRL, 1, movetoworkspace, 1
bind = $mod CTRL, 2, movetoworkspace, 2
bind = $mod CTRL, 3, movetoworkspace, 3
bind = $mod CTRL, 4, movetoworkspace, 4
bind = $mod CTRL, grave, movetoworkspace, special:terminal

bind = $mod, G, togglegroup
bind = $mod, Tab, changegroupactive, f

bind = $mod, mouse_down, workspace, e-1
bind = $mod, mouse_up, workspace, e+1

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bind = CTRL ALT, S, exec, playerctl --player=spotify play-pause # Spotify only play/plause 
bind = CTRL ALT, D, exec, playerctl --player=spotify next		# Spotify only next track
bind = CTRL ALT, A, exec, playerctl --player=spotify previous	# Spotify only previous track

