general {
    gaps_in = 1
    gaps_out = 0

    border_size = 2

    col.active_border = rgba(c75465ff)
    col.inactive_border = rgba(3b3c3fff)

    resize_on_border = false

    allow_tearing = false

    layout = master

    no_focus_fallback = true

    snap {
        enabled = true
        border_overlap = false
    }
}

group {
    col.border_active = rgb(c75465)
    col.border_inactive = rgb(7F8083)
    col.border_locked_active = rgb(4993C6)
    col.border_locked_inactive = rgb(3B3C3F)
    groupbar {
        col.active = rgba(00000000)
        col.inactive = rgba(00000000)
        col.locked_active = rgba(00000000)
        col.locked_inactive = rgba(00000000)
    }
xwayland {
    force_zero_scaling = true
}

decoration {
    rounding = 5
    rounding_power = 2
    active_opacity = 1
    inactive_opacity = 1

    dim_special = 0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = no

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade

    workspace_wraparound = true
}


master {
    new_status = slave
    mfact = 0.50
    new_on_top = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    font_family = monospace
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

debug {
    disable_logs = false
}

input {
    kb_layout = us

    follow_mouse = 1
    focus_on_close = 1

    sensitivity = 0

    numlock_by_default = true

    touchpad {
        scroll_factor = 0.33
	      natural_scroll = true
        disable_while_typing = true
    }
}

render {
    direct_scanout = false
}

group {
    insert_after_current = false
    drag_into_group = 1
    merge_floated_into_tiled_on_groupbar = true
    group_on_movetoworkspace = true

    col.border_active = rgba(c75465ff)
    col.border_inactive = rgba(3b3c3fff)
    col.border_locked_active = rgba(c75465ff)
    col.border_locked_inactive = rgba(3b3c3fff)

    groupbar {
        enabled = true
        scrolling = false
        height = 20
        indicator_height = 3
        render_titles = false
        font_family = monospace
        stacked = false

        rounding = 5
        rounding_power = 2
        round_only_edges = true
        keep_upper_gap = true

        col.active = rgba(c75465ff)
        col.inactive = rgba(3b3c3fff)
    }
}

gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_create_new = false
}

binds {
    workspace_back_and_forth = false
    hide_special_on_workspace_change = true
}

cursor {
    hide_on_key_press = true
    zoom_disable_aa = true
}

quirks {
    prefer_hdr = 0
}
