$terminal = sh -c "kitty @ --to unix:/tmp/kitty launch --type=tab || kitty --listen-on unix:/tmp/kitty & sleep 0.1 && hyprctl dispatch focuswindow 'class:^(kitty)$' || hyprctl dispatch focuswindow 'class:^(kitty)$'" # Kitty limited to single instance, bind opens a new tab instead
$code = sh -c "kitty @ --to unix:/tmp/kitty launch --type=tab nvim || (kitty --listen-on unix:/tmp/kitty nvim &) && sleep 0.1; hyprctl dispatch focuswindow 'class:^(kitty)$'" # Neovim
$filemanager = nautilus --no-desktop
$browser = zen-browser
$menu = tofi-drun -c ~/.config/tofi/config --drun-launch=true
$music = spotify
$notes = obsidian
$wallpaper = hyprpaper
$notifications = mako &
