windowrule {
    name = nemo
    match:class = nemo
    float = true
    size = 900 600
}
windowrule {
    name = Nautilus
    match:class = org.gnome.Nautilus
    float = true
    size = 900 600
}
windowrule {
    name = yad
    match:class = yad
    float = true
    size = 900 600
}
windowrule {
    name = Peazip
    match:class = Peazip
    float = true
    size = 900 600
}
windowrule {
    name = KDEConnect Daemon
    match:class = org.kde.kdeconnect.daemon
    float = true
}
windowrule {
    name = KDEConnect App
    match:class = org.kde.kdeconnect.app
    float = true
    size = 900 600
}
windowrule {
    name = screen-share-picker
    match:class = hyprland-share-picker
    float = true
    size = 400 400
    center = true
    group = barred
}
windowrule {
    name = Beeper
    match:class = BeeperTexts
    float = true
    size = 960 960
    max_size = 960 960
    move = 958 118
}

# Workspace 1
windowrule {
    name = Zen Browser
    match:title = ^(Zen Browser)$
    workspace = 1
    fullscreen_state = 2 0
}
windowrule {
    name = Zen Browser Library
    match:title = Library
    float = true
}
windowrule {
    name = qbittorent
    match:class = org.qbittorrent.qBittorrent
    workspace = 1
    group = set invade
}

windowrule {
    name = JDownloader2
    match:title = ^(JDownloader 2)$
    workspace = 1
}

# Workspace 2
windowrule {
    name = Vesktop
    match:class = vesktop
    workspace = 2
    float = true
    size = 960 960
    max_size = 960 960
    move = 958 118
    group = set invade
}

windowrule {
    name = steam
    match:class = steam
    workspace = 2
    float = true
    no_initial_focus = true
    group = set invade
}
windowrule {
    name = Steam
    match:class = Steam
    workspace = 2
    no_initial_focus = true
    group = set invade
}
windowrule {
    name = Steam2
    match:title = Steam
    workspace = 2
    size = 1024 768
    max_size = 1024 768
    min_size = 960 540
    move = 2 52
    group = set invade
}
windowrule {
    name = steam_app
    match:class = ^steam_app_
    workspace = 2
}
windowrule {
    name = steam_proton
    match:class = steam_proton
    workspace = 2
}

windowrule {
    name = Bottles
    match:class = com.usebottles.bottles
    workspace = 2
    float = true
    size = 600 600
    move = 2 478
    move = 1318 478
    group = barred
}
windowrule {
    name = Bottles2
    match:class = bottles
    size = 600 600
    move = 2 478
    move = 1318 478
    group = barred
}

windowrule {
    name = r2modman
    match:class = r2modman
    workspace = 2
    float = true
    persistent_size = true
    group = set invade
}

windowrule {
    name = Blender
    match:class = blender
    workspace = 2
}

# Workspace 3
windowrule {
    name = VLC
    match:class = vlc
    workspace = 3
}
windowrule {
    name = VLC File Opening Dialog
    match:title = ^(Select one or more files to open — VLC media player)$
    float = true
}
windowrule {
    name = VLC Directory Opening Dialog
    match:title = ^(Open Directory — VLC media player)$
    float = true
}
windowrule {
    name = Spotify
    match:class = Spotify
    workspace = 3
}

# Workspace 4
windowrule {
    name = Obsidian
    match:class = obsidian
    workspace = 4
}

# Special Workspace Terminal
windowrule {
    name = Kitty
    match:class = kitty
    workspace = special:terminal
    fullscreen_state = 2 0
}

layerrule {
    name = OSD
    match:namespace = indicator
    above_lock = 1
}

layerrule {
    name = notifications
    match:namespace = notifications-window
    no_screen_share = on
}

workspace = special:terminal, on-created-empty:$terminal
