windowrulev2 = float, class:org.gnome.Nautilus
windowrulev2 = size 900 600, class:org.gnome.Nautilus
windowrulev2 = float, class:nemo
windowrulev2 = float, class:org.kde.kdeconnect.daemon
windowrulev2 = float, class:org.kde.kdeconnect.app
windowrulev2 = size 900 600, class:org.kde.kdeconnect.app
windowrulev2 = float, class:yad
windowrulev2 = size 900 600, class:yad
windowrulev2 = float, class:Peazip

# Workspace 1
windowrulev2 = float, title:Library # Zen Browser windows
windowrulev2 = workspace 1, class:zen
windowrulev2 = fullscreenstate 2 0, title:^(Zen Browser)$

windowrulev2 = workspace 1, title:^(JDownloader 2)$

# Workspace 2
windowrulev2 = workspace 2, class:vesktop
windowrulev2 = float, class:vesktop
windowrulev2 = size 960 960, class:vesktop
windowrulev2 = maxsize 960 960, class:vesktop
windowrulev2 = move 958 118, class:vesktop # Move to Bottom-Right

windowrulev2 = workspace 2, class:steam
windowrulev2 = workspace 2, class:Steam
windowrulev2 = workspace 2, title:Steam
windowrulev2 = float, class:steam
windowrulev2 = size 1024 768, title:Steam
windowrulev2 = maxsize 1024 768, title:Steam
windowrulev2 = minsize 960 540, title:Steam
windowrulev2 = move 2 52, title:Steam # Move to Top-Left
windowrulev2 = noinitialfocus, class:steam
windowrulev2 = noinitialfocus, class:Steam

windowrulev2 = workspace 2, class:^steam_app_
windowrulev2 = workspace 2, class:steam_proton

windowrulev2 = workspace 2, class:com.usebottles.bottles
windowrulev2 = float, class:com.usebottles.bottles
windowrulev2 = size 600 600, class:com.usebottles.bottles
windowrulev2 = move 2 478, class:com.usebottles.bottles # Move to Bottom-Left
windowrulev2 = size 600 600, class:bottles
windowrulev2 = move 2 478, class:bottles

windowrulev2 = workspace 2, class:r2modman
windowrulev2 = float, class:r2modman
windowrulev2 = persistentsize, class:r2modman

windowrulev2 = workspace 1, class:BeeperTexts
windowrulev2 = float, class:BeeperTexts
windowrulev2 = size 960 960, class:BeeperTexts
windowrulev2 = maxsize 960 960, class:BeeperTexts
windowrulev2 = move 958 118, class:BeeperTexts # Move to Bottom-Right

windowrulev2 = workspace 2, class:blender

# Workspace 3
windowrulev2 = float, title:^(Select one or more files to open — VLC media player)$ # VLC File Opening Dialog
windowrulev2 = float, title:^(Open Directory — VLC media player)$ # VLC Directory Opening Dialog
windowrulev2 = workspace 3, class:vlc

windowrulev2 = workspace 3, class:Spotify
windowrulev2 = noinitialfocus, class:Spotify
windowrulev2 = fullscreenstate 1 0, class:Spotify

# Workspace 4
windowrulev2 = workspace 4, class:obsidian

# Special Workspace Terminal
windowrulev2 = workspace special:terminal, class:kitty
windowrulev2 = fullscreenstate 2 0, class:kitty

workspace = 1, name:web
workspace = 2, name:gaming
workspace = 3, name:media
workspace = 4, name:notes
