exec-once=/usr/lib/polkit-kde-authentication-agent-1

exec-once = hypridle
exec-once = $browser
exec-once = $music
exec-once = $notes
exec-once = $swww
exec-once = $wallpaper
exec-once = hyprpanel
exec-once = vesktop
exec-once = steam

exec-once = kdeconnect-cli --list-available           # Running this will Connect

