exec-once=/usr/lib/polkit-kde-authentication-agent-1

exec-once = hypridle
exec-once = hyprpanel
exec-once = $wallpaper
exec-once = $browser
exec-once = $music
exec-once = $notes
exec-once = $discord
exec-once = steam
exec-once = vesktop
exec-once = zen-browser
exec-once = spotify
exec-once = obsidian

exec-once = bluetoothctl connect 2C:BE:EB:DE:96:D2    # Connect to my CMF buds
exec-once = kdeconnect-cli --list-available           # Running this will Connect
