windowrulev2 = float, class:org.gnome.Nautilus

# Workspace 1
windowrulev2 = float, title:Library # Zen Browser windows
windowrulev2 = workspace 1, class:zen
windowrulev2 = workspace 1, title:^(JDownloader 2)$

# Workspace 2
windowrulev2 = workspace 2, class:discord
windowrulev2 = float, class:discord
windowrulev2 = size 960 960, class:discord
windowrulev2 = maxsize 960 960, class:discord
windowrulev2 = move 958 118, class:discord # Move to Bottom-Right
windowrulev2 = noinitialfocus, class:discord

windowrulev2 = workspace 2, class:steam
windowrulev2 = float, class:steam
windowrulev2 = size 1024 768, title:Steam
windowrulev2 = maxsize 1024 768, title:Steam
windowrulev2 = minsize 960 540, title:Steam
windowrulev2 = move 2 47, title:Steam # Move to Top-Left
windowrulev2 = noinitialfocus, class:steam

windowrulev2 = workspace 2, class:^steam_app_
windowrulev2 = workspace 2, class:steam_proton

windowrulev2 = workspace 2, class:com.usebottles.bottles
windowrulev2 = float, class:com.usebottles.bottles
windowrulev2 = size 600 600, class:com.usebottles.bottles
windowrulev2 = move 2 478, class:com.usebottles.bottles # Move to Bottom-Left
windowrulev2 = noinitialfocus, class:com.usebottles.bottles

windowrulev2 = workspace 2, class:r2modman
windowrulev2 = float, class:r2modman
windowrulev2 = persistentsize, class:r2modman

# Workspace 3
windowrulev2 = float, title:^(Select one or more files to open)$ # VLC File Opening Dialog
windowrulev2 = float, title:^(Open Directory)$ # VLC Directory Opening Dialog
windowrulev2 = workspace 3, class:vlc
windowrulev2 = fullscreenstate 1 0, title:^(VLC media player)$

windowrulev2 = workspace 3, class:Spotify
windowrulev2 = noinitialfocus, class:Spotify

# Workspace 4
windowrulev2 = workspace 4, class:obsidian
windowrulev2 = noinitialfocus, class:obsidian

# Special Workspace Terminal
windowrulev2 = workspace special:terminal, class:kitty

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

workspace = 1, name:web
workspace = 2, name:gaming
workspace = 3, name:media
workspace = 4, name:notes
