windowrulev2 = float, center, class:org.gnome.Nautilus

# Workspace 1
windowrulev2 = workspace 1, class:zen
windowrulev2 = workspace 1, title:^(JDownloader 2)$

# Workspace 2
windowrulev2 = workspace 2, class:discord
windowrulev2 = float, class:discord
windowrulev2 = persistentsize, class:discord

windowrulev2 = workspace 2, class:steam
windowrulev2 = float, class:steam
windowrulev2 = persistentsize, class:steam
windowrulev2 = workspace 2, class:^steam_app_
windowrulev2 = workspace 2, class:steam_proton

windowrulev2 = float, workspace 2, class:com.usebottles.bottles

# Workspace 3
windowrulev2 = workspace 3, fullscreenstate 1 0, class:vlc
windowrulev2 = workspace 3, fullscreenstate 1 0, class:Spotify

# Workspace 4
windowrulev2 = workspace 4, fullscreenstate 1 0, class:obsidian

# Special Workspace Terminal
windowrulev2 = workspace special:terminal, class:kitty

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

workspace = 1, name:web
workspace = 2, name:gaming
workspace = 3, name:media
workspace = 4, name:notes
